### ISSUE TITLE
Watch owned resources regardless of owner's version

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#1399]
**Describe the bug**
Our controllers watch for changes in controlled resources. E.g. Channel watches for changes in controlled PullSubscriptions.

However, it checks the exact GVK, not just the GK. Thus it worked great when there was only one version of the owning resource. But as soon as there are multiple versions, the controller will only watch for changes if the owner is a specific version.

 **Expected behavior**
Controllers should watch for all owned resources, regardless of the version of the owner.

For example, the Channel controller should rereconcile the `demo` Channel for resources with any of the following owners (note that the only difference is the owner's version).

```yaml
    ownerReferences:
    - apiVersion: messaging.cloud.google.com/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Channel
      name: demo
      uid: 7b0d0f79-a304-444a-820d-f1918c3ccdad
---
    ownerReferences:
    - apiVersion: messaging.cloud.google.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Channel
      name: demo
      uid: 7b0d0f79-a304-444a-820d-f1918c3ccdad
---
    ownerReferences:
    - apiVersion: messaging.cloud.google.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: Channel
      name: demo
      uid: 7b0d0f79-a304-444a-820d-f1918c3ccdad
```

 **To Reproduce**
1. Create a Channel.
1. Edit the Topic made by the Channel, altering only the version of the owning Channel reference.
1. Delete the Topic made by the Channel.

We would expect the Channel reconciler to immediately notice and create a new Topic. What we actually see is that the Channel doesn't notice and we need to wait until the next normal reconcile period to have the Channel fixed.

 **Knative-GCP release version**
0.16

 **Additional context**
This can be fixed, as is done in #1398, by replacing the `FilterFunc`:

```golang
FilterFunc: controller.Filter(v1beta1.SchemeGroupVersion.WithKind("Channel")),
```

WIth `FilterControllerGK`:

```golang
FilterFunc: controller.FilterControllerGK(v1beta1.Kind("Channel")),
```
