### ISSUE TITLE
Inaccurate TopicReady status for both GCP and eventing broker users

### ISSUE THREAD

**Issue by cathyzhyi** [google/knative-gcp#1687]
**Describe the bug**
When a non GCP broker is recreated from a GCP broker, trigger status's `TopicReady` condition could show `True` even when the topic is not properly finalized. This can results in unnoticed dangling topic. 
When a user installs a non GCP broker and creates  triggers for it, the triggers can show `TopicReady: True` even though it doesn't matter to them. 
After user of eventing broker delete the broker of a trigger, they might see `TopicReady: Unknown/True` even though it doesn't matter to them.

 **Expected behavior**
`TopicReady` shouldn't appear in the trigger status if the trigger has never pointed to a GCP broker. `TopicReady` should accurately report the actually status of the finalized/reconciled topic.

 **To Reproduce**

1.  install knative eventing
2. install mt-channel-broker and sugar controller 
3. kubectl create namespace test-tigger
4. kubectl label namespace default knative-eventing-injection=enabled
5. install knative-gcp
6. create a trigger with the following yaml file
```
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: my-trigger
  namespace: test-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: test-trigger
```
7. `kubectl get trigger my-trigger -n test-trigger -o ymal` shows `TopicReady` condition

 **Knative-GCP release version**

 **Additional context**
The root cause is because a limitation in the current code where genreconciler adding `googlecloud` finalizers uniformly and we can't accurately tell if the trigger once belonged to a GCP broker or not. The details of a proper fix are described in https://github.com/google/knative-gcp/issues/1164.

Until the proper fix is implemented, we suggest the users to avoid recreating a GCP broker with a different brokerclass which might cause unnoticed dangling topic. The users of non GCP broker should just ignore the `TopicReady` condition in the trigger status.
