### ISSUE TITLE
Installation of Knative-GCP v0.22.0 does not work due to inaccessible images

### ISSUE THREAD

**Issue by meteatamel** [google/knative-gcp#2204]
**Describe the bug**
I tried to install knative-gcp v0.22.0 in a cluster that already has Knative Serving and Eventing installed with the following script I have [here](https://github.com/meteatamel/knative-tutorial/blob/master/setup/install-knative-gcp). 

Everything seemed successful but when I do look at pods, I see `ImagePullBackOff`:

```
kubectl get pods -n cloud-run-events
NAME                          READY   STATUS             RESTARTS   AGE
controller-78dc7b9568-fb87m   0/1     ImagePullBackOff   0          20m
webhook-74847d744f-79ppf      0/1     ImagePullBackOff   0          20m
```

When I get the pods, this is what I see:

```
kubectl get pod controller-78dc7b9568-fb87m -n cloud-run-events -oyaml
state:
      waiting:
        message: Back-off pulling image "gcr.io/knative-gcp/github.com/google/knative-gcp/cmd/controller@sha256:0ec02ca2a960b4515829531132eeb9e8e115773e912d9b9fed1e1d9a8e45fd94"
        reason: ImagePullBackOff
```

```
kubectl get pod webhook-74847d744f-79ppf -n cloud-run-events -oyaml
    state:
      waiting:
        message: Back-off pulling image "gcr.io/knative-gcp/github.com/google/knative-gcp/cmd/webhook@sha256:96ad5b184a244b87ecd45ee7b115ccc9b7f8fb0bb44b970ea3989ad2b33b86a3"
```

When I try Docker to pull these images, they are not accessible:

```
docker pull gcr.io/knative-gcp/github.com/google/knative-gcp/cmd/controller@sha256:0ec02ca2a960b4515829531132eeb9e8e115773e912d9b9fed1e1d9a8e45fd94
Error response from daemon: pull access denied for gcr.io/knative-gcp/github.com/google/knative-gcp/cmd/controller, repository does not exist or may require 'docker login': denied: Permission denied for "sha256:0ec02ca2a960b4515829531132eeb9e8e115773e912d9b9fed1e1d9a8e45fd94" from request "/v2/knative-gcp/github.com/google/knative-gcp/cmd/controller/manifests/sha256:0ec02ca2a960b4515829531132eeb9e8e115773e912d9b9fed1e1d9a8e45fd94".
```

```
docker pull gcr.io/knative-gcp/github.com/google/knative-gcp/cmd/webhook@sha256:96ad5b184a244b87ecd45ee7b115ccc9b7f8fb0bb44b970ea3989ad2b33b86a3
Error response from daemon: pull access denied for gcr.io/knative-gcp/github.com/google/knative-gcp/cmd/webhook, repository does not exist or may require 'docker login': denied: Permission denied for "sha256:96ad5b184a244b87ecd45ee7b115ccc9b7f8fb0bb44b970ea3989ad2b33b86a3" from request "/v2/knative-gcp/github.com/google/knative-gcp/cmd/webhook/manifests/sha256:96ad5b184a244b87ecd45ee7b115ccc9b7f8fb0bb44b970ea3989ad2b33b86a3".
```

 **Expected behavior**
Pods start successfully.
