### ISSUE TITLE
Use PROJECT_ID from the google-cloud-key secret

### ISSUE THREAD

**Issue by sayanh** [google/knative-gcp#255]
Right now, PROJECT_ID should be part of the channel template in `default-ch-webhook` spec. Something like this:
```
apiVersion: v1
data:
  default-ch-config: |
    clusterDefault:
      apiVersion: messaging.cloud.run/v1alpha1
      kind: Channel
      spec:
        project: my-project
```

As secret `google-cloud-key` is already containing PROJECT_ID, it can be picked up from there rather than having in channel template.
