### ISSUE TITLE
PropagateStatus when Topic Fails in PullSubscription

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#313]
- We should propagate the status message when the topic does not exist in a pull subscription.
- This will also help debug the new `PubSub` source.

**Comment by nachocano** [comment]
fyi @n3wscott

**Comment by akashrv** [comment]
@nachocano What happens today? Could you explain actual and expected behavior from users perspective? Will help in triage.

**Comment by nachocano** [comment]
the message that the topic does not exist is not propagated back up, thus is not that easy to debug... this is not an alpha blocker, it will be a nice to have.
@n3wscott mentioned that there is a message in the jobs that we can use to add that info...

**Comment by nachocano** [comment]
For example, if you create a PubSub as follows, with a topic that does not exist, you won't get a clear error.

```
apiVersion: events.cloud.google.com/v1alpha1
kind: PubSub
metadata:
  name: wrong-topic
spec:
  topic: non-existing-topic
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
```
