### ISSUE TITLE
[BUG] Incorrect datacontenttype on emitted cloudevent acording to spec

### ISSUE THREAD

**Issue by grebois** [google/knative-gcp#401]
According to Cloudevents spec 0.3 https://github.com/cloudevents/spec/blob/v0.3/json-format.md#32-examples the field `datacontenttype` should reflect the content type of the data of the messsage, also in case of binary data, this should be encoded in base64, for example on a `thrift` message im getting this cloudevent:

```
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 0.3
  type: com.google.cloud.pubsub.topic.publish
  source: //pubsub.googleapis.com/projects/XXXXXX/topics/XXXXXX
  id: 831998525658724
  time: 2019-11-04T16:42:14.498Z
  datacontenttype: application/json
Extensions,
  knativecemode: binary
Data,

81.200.207.97
�n7K�Z
      �UTF-8
            �ssc-0.15.0-googlepubsub
```

when it should be according to https://github.com/cloudevents/spec/blob/v0.3/json-format.md#32-examples:

```
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 0.3
  type: com.google.cloud.pubsub.topic.publish
  source: //pubsub.googleapis.com/projects/XXXXXX/topics/XXXXXX
  id: 831998525658724
  time: 2019-11-04T16:42:14.498Z
  datacontenttype: application/vnd.apache.thrift.binary
Extensions,
  knativecemode: binary
Data,
  base64 encoded data 
```

and for v1.0 https://github.com/cloudevents/spec/blob/v1.0/json-format.md#32-examples the data field changes to data_base64:

```
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "B234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "application/vnd.apache.thrift.binary",
    "data_base64" : "... base64 encoded string ..."
}
```

furthermore this also fails with any other content than json, for example XML will also fail as the data is not json valid format and fails to decode with any cloudevent SDK

```
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "application/json",
    "data" : "<much wow=\"xml\"/>"
}
```

as an easy fix for this problem it would be nice if we could overwrite the datacontenttype as it might be difficult sometimes to detect the correct message type with something like:

```
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: demo
spec:
  datacontenttype: application/vnd.apache.thrift.binary
  channel:
    apiVersion: messaging.cloud.google.com/v1alpha1
    kind: Channel
    name: demo
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
```

or/and

```
apiVersion: pubsub.cloud.google.com/v1alpha1
kind: PullSubscription
metadata:
  name: TOPIC_NAME-source
spec:
  topic: TOPIC_NAME
  datacontenttype: application/vnd.apache.thrift.binary
  sink:
    apiVersion: v1
    kind: Service
    name: event-display
```
