### ISSUE TITLE
Support trigger identity in broker

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#727]
**Problem**
In our broker, we should enable broker to send events with identities. The reason is documented in the [policy design](https://docs.google.com/document/d/1Nymrlp__dXKsp02Dpif0GN_Pskm6YXv6WjeF8trYzzk/edit#bookmark=id.8i81ieryxdes).

**Proposal**
Since it's unlikely all broker classes will support this feature (at least at the beginning), it's hard to add this as part of the trigger API. We can leverage trigger annotation for this purpose in the following way.

```yaml
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: my-trigger
  annotations:
    eventing.knative.dev/trigger-identity: "serviceaccount:default/my-serviceaccount"
```

For us, we should also support GSA, e.g.

```yaml
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: my-trigger
  annotations:
    eventing.knative.dev/trigger-identity: "gserviceaccount:my-serviceaccount@my-project.iam.gserviceaccount.com"
```

In fanout service, we can add modules to retrieve tokens for service accounts and attach them to outbound events.
